# This is a basic workflow to help you get started with Actions

name: Build and Deploy to AWS Lambda

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main" ]

env:
  AWS_REGION: us-east-1
  ENQUEUE_LAMBDA_FUNCTION_NAME: TranscodingServiceQueuePublisher
  PROCESS_LAMBDA_FUNCTION_NAME: TranscodingServiceQueueProcessor
  ARTIFACT_NAME: VideoTranscoderLambda.jar

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Code
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v3.14.1
        with:
         java-version: '17'
         distribution: 'temurin'

      - name: Build Package
        run: mvn clean package -DskipTests

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: lambda-artifact
          path: target/${{ env.ARTIFACT_NAME }}

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4.1.0
        with:
          aws-region: us-east-1
          aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID}}
          aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}

      - name: Deploy Code to Lambda Function for Handling S3 Uploads
        run: aws lambda update-function-code --function-name ${{env.ENQUEUE_LAMBDA_FUNCTION_NAME}} --region ${{env.AWS_REGION}} --zip-file fileb://target/${{env.ARTIFACT_NAME}}

      - name: Deploy Code to Lambda Function for Handling Queue Messages
        run: aws lambda update-function-code --function-name ${{env.PROCESS_LAMBDA_FUNCTION_NAME}} --region ${{env.AWS_REGION}} --zip-file fileb://target/${{env.ARTIFACT_NAME}}
